networks:
  rinha-net:
    driver: bridge

  payment-processor:
    external: true

services:
  api-1:
    build:
      context: .
      dockerfile: Rinha.Api/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    container_name: api-1
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "58MB"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:9999
      - ASPNETCORE_ENVIRONMENT=Production
      - REDIS_ENDPOINT=redis:6379,abortConnect=false
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    expose:
      - "9999"
    depends_on:
      - redis
    networks:
      - rinha-net
      - payment-processor
      
  api-2:
    build:
      context: .
      dockerfile: Rinha.Api/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    container_name: api-2
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "58MB"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:9999
      - ASPNETCORE_ENVIRONMENT=Production
      - REDIS_ENDPOINT=redis:6379,abortConnect=false
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    expose:
      - "9999"
    depends_on:
      - redis
    networks:
      - rinha-net
      - payment-processor
  api-3:
    build:
      context: .
      dockerfile: Rinha.Api/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    container_name: api-3
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "58MB"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:9999
      - ASPNETCORE_ENVIRONMENT=Production
      - REDIS_ENDPOINT=redis:6379,abortConnect=false
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    expose:
      - "9999"
    depends_on:
      - redis
    networks:
      - rinha-net
      - payment-processor
  api-4:
    build:
      context: .
      dockerfile: Rinha.Api/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    container_name: api-4
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "58MB"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:9999
      - ASPNETCORE_ENVIRONMENT=Production
      - REDIS_ENDPOINT=redis:6379,abortConnect=false
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    expose:
      - "9999"
    depends_on:
      - redis
    networks:
      - rinha-net
      - payment-processor
      
  redis:
    image: redis:7.2-alpine
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "59MB"
    expose:
      - "6379"
    networks:
      - rinha-net

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "59MB"
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
      - api-3
    networks:
      - rinha-net