@baseUrl = http://localhost:9999
@adminBaseUrl = http://localhost:9999

### Criar pagamento
POST {{baseUrl}}/payments
Content-Type: application/json

{
  "correlationId": "c0a80101-0000-0000-0000-000000001110",
  "amount": 100.0
}

### Obter resumo dos pagamentos
GET {{baseUrl}}/payments-summary
Accept: application/json


### Este endpoint exclui todos os pagamentos do banco de dados e serve apenas para facilitar o desenvolvimento.
PUT {{baseUrl}}/admin/purge-payments